# Ionos Deploy Now Configuration
# This file configures deployment settings for Ionos Deploy Now

# Project configuration
project:
  name: 'baphomet-ui'

# Custom domain configuration
domains:
  - 'baphomet.collinlucke.com'

# Build configuration
build:
  commands:
    - 'pnpm install'
    - 'pnpm run build'
  outputDirectory: 'dist'

# Environment variables (these will be set in GitHub secrets)
environment:
  - GIT_REGISTRY_TOKEN
  - GRAPHQL_BAPHOMET_SERVER_RENDER_URL

# SPA routing configuration
routing:
  rewrites:
    - source: '/**'
      destination: '/index.html'
