version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:80'
    environment:
      NODE_ENV: 'production'
      SERVER_BASE_URL: ${SERVER_BASE_URL}
      GIT_REGISTRY_TOKEN: ${GIT_REGISTRY_TOKEN}
