services:
  app:
    restart: no
    networks:
      - baphomet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    environment:
      - NODE_ENV=${NODE_ENV}
      - SERVER_BASE_URL=${SERVER_BASE_URL}
      - GIT_REGISTRY_TOKEN=${GIT_REGISTRY_TOKEN}

networks:
  baphomet:
    driver: bridge
