services:
  app:
    image: collinlucke/baphomet-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    environment:
      NODE_ENV: 'production'
      SERVER_BASE_URL: ${SERVER_BASE_URL}
      GIT_REGISTRY_TOKEN: ${GIT_REGISTRY_TOKEN}
