services:
  app:
    image: baphomet-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:80'

    environment:
      NODE_ENV: 'production'
      SERVER_BASE_URL: ${SERVER_BASE_URL}

    secrets:
      - GIT_REGISTRY_TOKEN

secrets:
  GIT_REGISTRY_TOKEN:
    external: true
