services:
  - type: static
    name: baphomet-ui
    buildCommand: cp .npmrc.render .npmrc && pnpm build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      - paths:
          - src/**
          - public/**
          - package.json
          - pnpm-lock.yaml
          - tsconfig.json
          - vite.config.mjs
          - .npmrc.render
    envVars:
      - key: GRAPHQL_BAPHOMET_SERVER_RENDER_URL
        value: https://baphomet-server.onrender.com/graphql
      - key: GIT_REGISTRY_TOKEN
        sync: false
