services:
  - type: web
    name: baphomet-ui
    env: static
    buildCommand: |
      # Set up GitHub Packages authentication
      echo "//npm.pkg.github.com/:_authToken=${GIT_REGISTRY_TOKEN}" > .npmrc
      echo "@collinlucke:registry=https://npm.pkg.github.com" >> .npmrc

      # Install dependencies
      echo "Installing dependencies..."
      pnpm install --frozen-lockfile --verbose

      # Build the application
      echo "Building application..."
      pnpm build

      # Cleanup sensitive data
      rm -f .npmrc
    staticPublishPath: ./dist
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - pnpm-lock.yaml
        - tsconfig.json
        - vite.config.mjs
    envVars:
      - key: GRAPHQL_BAPHOMET_SERVER_RENDER_URL
        value: https://baphomet-server.onrender.com/graphql
      - key: GIT_REGISTRY_TOKEN
        sync: false # This makes it a secret environment variable
