services:
  - type: web
    name: baphomet-ui
    env: node
    buildCommand: |
      echo "Installing pnpm..."
      npm install -g pnpm@8

      echo "Setting up .npmrc..."
      echo "shamefully-hoist=true" > .npmrc
      echo "strict-peer-dependencies=false" >> .npmrc
      echo "@collinlucke:registry=https://npm.pkg.github.com" >> .npmrc
      echo "//npm.pkg.github.com/:_authToken=${GIT_REGISTRY_TOKEN}" >> .npmrc

      # Build phantomartist locally
      echo "Cloning and building phantomartist..."
      git clone https://github.com/collinlucke/phantomartist.git
      cd phantomartist
      pnpm install
      pnpm build
      cd ..

      # Link phantomartist locally
      echo "Installing and linking dependencies..."
      pnpm install --frozen-lockfile --verbose
      pnpm link ./phantomartist

      # Build the application
      echo "Starting build process..."
      set -e  # Make script exit on any error
      pnpm build

      # Verify build output
      echo "Verifying build output..."
      if [ ! -d "dist" ]; then
        echo "Error: dist directory not found!"
        exit 1
      fi
      echo "Build output:"
      ls -la dist/

      rm -f .npmrc
    startCommand: pnpm serve
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - pnpm-lock.yaml
        - tsconfig.json
        - vite.config.mjs
    envVars:
      - key: GRAPHQL_BAPHOMET_SERVER_RENDER_URL
        value: https://baphomet-server.onrender.com/graphql
      - key: GIT_REGISTRY_TOKEN
        sync: false # This makes it a secret environment variable
