services:
  - type: static
    name: baphomet-ui
    buildCommand: |
      echo "Setting up .npmrc..."
      cp .npmrc.render .npmrc
      echo "Installing dependencies..."
      pnpm install --no-frozen-lockfile
      echo "Building project..."
      pnpm build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: GRAPHQL_BAPHOMET_SERVER_RENDER_URL
        value: https://baphomet-server.onrender.com/graphql
      - key: GIT_REGISTRY_TOKEN
        sync: false
