services:
  - type: static
    name: baphomet-ui
    buildCommand: |
      # Install Node.js
      export NODE_VERSION=18
      export PATH="/opt/render/project/node/bin:$PATH"
      # Install pnpm
      echo "Installing pnpm..."
      npm install -g pnpm@8

      # Setup Node environment
      echo "Setting up Node environment..."
      export NODE_VERSION=22
      export NODE_ENV=production

      # Setup .npmrc
      echo "Setting up .npmrc..."
      echo "shamefully-hoist=true" > .npmrc
      echo "strict-peer-dependencies=false" >> .npmrc

      # Debug
      echo "Node version: $(node --version)"
      echo "PNPM version: $(pnpm --version)"

      # Clear and reinstall
      echo "Installing dependencies..."
      rm -f pnpm-lock.yaml
      pnpm install --no-frozen-lockfile

      # Build
      echo "Starting build process..."
      set -e
      pnpm build

      # Cleanup
      rm -f .npmrc

      # Verify build output
      echo "Verifying build output..."
      if [ ! -d "dist" ]; then
        echo "Error: dist directory not found!"
        exit 1
      fi
      echo "Build output:"
      ls -la dist/

      rm -f .npmrc
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      paths:
        - src/**
        - public/**
        - package.json
        - pnpm-lock.yaml
        - tsconfig.json
        - vite.config.mjs
    envVars:
      - key: GRAPHQL_BAPHOMET_SERVER_RENDER_URL
        value: https://baphomet-server.onrender.com/graphql
      - key: GIT_REGISTRY_TOKEN
        sync: false # This makes it a secret environment variable
