export const ITEM_CATEGORIES = [
  'Annuals',
  'Artificial Turf',
  'Bulbs',
  'Bulk Materials',
  'Chemicals',
  'Christmas Lights',
  'Compost',
  'Demolition & Disposal',
  'Drainage',
  'Drainage Supplies',
  'Evergreens',
  'Fencing',
  'Grass Seed',
  'Grasses',
  'Ground Cover',
  'Hardgoods',
  'Hardscape',
  'Irrigation',
  'Irrigation Materials',
  'Labor',
  'Lighting',
  'Maintenance',
  'Misc Install Materials',
  'Mulch',
  'Other',
  'Pavers',
  'Perennials',
  'Pipe',
  'Rental Equipment',
  'Rock',
  'Shrubs',
  'Snow',
  'Sod / Lawn',
  'Soil',
  'Soil Amendments',
  'Stakes',
  'Stone',
  'Sub',
  'Topsoil',
  'Tree',
  'Weed Barrier'
] as const;
