version: 1.0.0
build:
  outputDirectory: dist
  commands:
    - pnpm install
    - pnpm run build
routing:
  fallback: index.html
domains:
  - baphomet.collinlucke.com
headers:
  - source: "/**"
    headers:
      - key: "X-Frame-Options"
        value: "DENY"
      - key: "X-Content-Type-Options"
        value: "nosniff"
      - key: "Cache-Control"
        value: "public, max-age=31536000"
  - source: "/index.html"
    headers:
      - key: "Cache-Control"
        value: "no-cache"
