# Deploy Now configuration file
# This file configures deployment settings

# Distribution directory
distDir: dist

# Routing configuration for SPA
routes:
  fallback: index.html

# Custom domains
domains:
  - baphomet.collinlucke.com

# Header configuration
headers:
  - source: '/**'
    headers:
      - key: 'Cache-Control'
        value: 'public, max-age=31536000'
  - source: '/index.html'
    headers:
      - key: 'Cache-Control'
        value: 'no-cache'
