name: Deploy Baphomet UI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Create .npmrc
        run: |
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "@collinlucke:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GIT_REGISTRY_TOKEN }}" >> ~/.npmrc
      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t collinlucke/baphomet-ui . --build-arg NODE_ENV='production' --build-arg VITE_SERVER_BASE_URL=`${{secrets.VITE_SERVER_BASE_URL}}`
      - name: Publish Image to Docker Hub
        run: docker push collinlucke/baphomet-ui:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull collinlucke/baphomet-ui:latest
      - name: Delete Old Container
        run: docker rm -f baphomet-ui-container
      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name baphomet-ui-container collinlucke/baphomet-ui
