name: Build and Deploy to Render

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup .npmrc for GitHub packages
        env:
          GIT_REGISTRY_TOKEN: ${{ secrets.GIT_REGISTRY_TOKEN }}
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "@collinlucke:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GIT_REGISTRY_TOKEN}" >> .npmrc

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build with secrets
        env:
          VITE_GRAPHQL_BAPHOMET_SERVER_RENDER_URL: https://baphomet-server.onrender.com/graphql
          GIT_REGISTRY_TOKEN: ${{ secrets.GIT_REGISTRY_TOKEN }}
        run: pnpm build

      - name: Deploy to Render
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -n "$RENDER_DEPLOY_HOOK" ]; then
            echo "🚀 Triggering Render deployment..."
            curl -X POST "$RENDER_DEPLOY_HOOK"
            echo "✅ Deployment triggered!"
          else
            echo "⚠️  No RENDER_DEPLOY_HOOK found, skipping Render deployment"
          fi
