name: Render Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Setup environment
        run: |
          echo "shamefully-hoist=true" > .npmrc
          echo "strict-peer-dependencies=false" >> .npmrc
          echo "@collinlucke:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GIT_REGISTRY_TOKEN }}" >> .npmrc

      - name: Verify npmrc
        run: |
          echo "Checking .npmrc content (auth token hidden):"
          cat .npmrc | sed 's/authToken=.*/authToken=[hidden]/'
          if [ -z "${{ secrets.GIT_REGISTRY_TOKEN }}" ]; then
            echo "ERROR: GIT_REGISTRY_TOKEN is empty!"
            exit 1
          fi
          echo "Auth token length: ${#GIT_REGISTRY_TOKEN}"
        env:
          GIT_REGISTRY_TOKEN: ${{ secrets.GIT_REGISTRY_TOKEN }}

      - name: Install dependencies
        env:
          GIT_REGISTRY_TOKEN: ${{ secrets.GIT_REGISTRY_TOKEN }}
        run: |
          echo "Testing package access..."
          pnpm view @collinlucke/phantomartist@1.4.0 || exit 1
          echo "Package is accessible, proceeding with install..."
          pnpm install

      - name: Build
        run: pnpm build
        env:
          GRAPHQL_BAPHOMET_SERVER_RENDER_URL: ${{ secrets.GRAPHQL_BAPHOMET_SERVER_RENDER_URL }}
